#!/usr/bin/env bash
# Installs the Orca Kanban agent integration:
#   1. a `kanban` wrapper on PATH
#   2. the skill where omp and Claude Code both look for it (~/.claude/skills)
#   3. a pointer block in the global AGENTS.md files that codex and cursor read
#
# Idempotent: re-running refreshes the skill and rewrites the AGENTS.md block in
# place, so an updated block reaches agents that were set up earlier.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_SRC="$REPO_DIR/skills/orca-kanban/SKILL.md"
BLOCK_SRC="$REPO_DIR/integrations/AGENTS.md.block"

say() { printf '  %-46s %s\n' "$1" "$2"; }

# ---------------------------------------------------------------- 1. PATH shim
BIN_DIR="${ORCA_KANBAN_BIN_DIR:-$HOME/bin}"
[ -d "$BIN_DIR" ] || BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/kanban" <<EOF
#!/usr/bin/env bash
# Generated by orca-kanban/integrations/install.sh
exec node "$REPO_DIR/src/cli.ts" "\$@"
EOF
chmod +x "$BIN_DIR/kanban"
say "kanban wrapper" "$BIN_DIR/kanban"

case ":$PATH:" in
	*":$BIN_DIR:"*) ;;
	*) say "WARNING" "$BIN_DIR is not on PATH — add it to your shell profile" ;;
esac

# --------------------------------------------------- 2. skill (omp + Claude Code)
# omp and Claude Code both discover skills from ~/.claude/skills.
SKILL_DIR="${ORCA_KANBAN_SKILL_DIR:-$HOME/.claude/skills}/orca-kanban"
mkdir -p "$SKILL_DIR"
cp "$SKILL_SRC" "$SKILL_DIR/SKILL.md"
say "skill (omp + Claude Code)" "$SKILL_DIR/SKILL.md"

# ------------------------------------------- 3. AGENTS.md pointer (codex, cursor)
# Rewrites the delimited block in place, leaving everything else in the file alone.
# Skipping when the markers exist would strand old text on machines set up earlier.
add_block() {
	local target="$1"
	mkdir -p "$(dirname "$target")"

	if [ -f "$target" ] && grep -q 'BEGIN orca-kanban' "$target"; then
		if grep -q 'END orca-kanban' "$target"; then
			local tmp
			tmp="$(mktemp)"
			# Copy everything outside the markers, then drop our block back in its place.
			awk -v block="$BLOCK_SRC" '
				/BEGIN orca-kanban/ { inside = 1; while ((getline line < block) > 0) print line; close(block); next }
				/END orca-kanban/   { inside = 0; next }
				!inside             { print }
			' "$target" > "$tmp"
			mv "$tmp" "$target"
			say "AGENTS.md block refreshed" "$target"
		else
			say "AGENTS.md block LEFT ALONE (no END marker)" "$target"
		fi
		return
	fi

	[ -f "$target" ] && printf '\n' >> "$target"
	cat "$BLOCK_SRC" >> "$target"
	say "AGENTS.md block added" "$target"
}

add_block "$HOME/.codex/AGENTS.md"
add_block "$HOME/AGENTS.md"

printf '\nDone. Try: kanban help\n'
